// GreenBrain money-result + pattern-memory overlay.
// Primary objective shown to the user: did the closed investment make or lose money?
(function () {
  function moneyOutcome(row) {
    const result=Number(row?.result||0), risk=Math.max(0,Number(row?.riskAmount||0));
    const r=risk>0?result/risk:null;
    if(result>0)return{label:"MADE MONEY",className:"money-win",detail:`+$${result.toFixed(2)}`,r:r===null?"":`+${r.toFixed(2)}R`};
    if(result<0)return{label:"LOST MONEY",className:"money-loss",detail:`-$${Math.abs(result).toFixed(2)}`,r:r===null?"":`${r.toFixed(2)}R`};
    return{label:"NO PROFIT / LOSS",className:"money-flat",detail:"$0.00",r:risk>0?"0.00R":""};
  }
  function patternOf(row){const p=row?.pattern||{};return{key:p.key||row?.patternKey||"UNCLASSIFIED",setup:p.setup||row?.strategyId||"—",trend:p.trend||row?.regime||"—",volatility:p.volatilityBucket||"—",location:p.rangeLocation||"—",session:p.session||"—"};}
  function patternStats(history=[]){const map=new Map();history.forEach(row=>{const p=patternOf(row);if(p.key==="UNCLASSIFIED")return;const result=Number(row.result||0),risk=Math.max(0,Number(row.riskAmount||0));const x=map.get(p.key)||{...p,samples:0,wins:0,losses:0,net:0,rSum:0,rCount:0};x.samples++;x.net+=result;if(result>0)x.wins++;else if(result<0)x.losses++;if(risk>0){x.rSum+=result/risk;x.rCount++;}map.set(p.key,x);});return[...map.values()].map(x=>({...x,winRate:x.samples?x.wins/x.samples:0,expectancyR:x.rCount?x.rSum/x.rCount:0,profitable:x.net>0})).sort((a,b)=>b.net-a.net);}

  const style=document.createElement("style");style.textContent=`
    .history-table .row{grid-template-columns:.65fr .7fr .65fr .75fr 1.25fr 1.05fr}.money-signal,.pattern-pill{display:inline-flex;align-items:center;gap:6px;width:max-content;max-width:100%;border:1px solid var(--line2);border-radius:999px;padding:5px 9px;font-size:8px;font-weight:850;letter-spacing:.055em}.money-signal::before{content:"";width:7px;height:7px;border-radius:50%;background:currentColor;box-shadow:0 0 10px currentColor}.money-win{color:var(--accent);border-color:#315d3c;background:#102017}.money-loss{color:var(--red);border-color:#5b2e31;background:#1b1011}.money-flat{color:var(--amber);border-color:#5c4c28;background:#19160e}.money-amount{font-size:10px}.money-r{opacity:.62;font-weight:650}.pattern-pill{color:#b9c4bd;background:#0b100d;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pattern-memory{margin:10px 0}.pattern-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:18px}.pattern-card{border:1px solid var(--line);background:#0a0e0c;border-radius:8px;padding:13px;display:grid;gap:7px}.pattern-card strong{font-size:11px;overflow:hidden;text-overflow:ellipsis}.pattern-card small{font-size:8px;color:var(--muted);line-height:1.5}.pattern-score{font-size:18px!important}.pattern-learning{color:var(--amber)}
    @media(max-width:900px){.pattern-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.history-table{overflow-x:auto}.history-table .row{min-width:780px}.pattern-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(style);

  const historyPanel=document.getElementById("history");if(historyPanel){const section=document.createElement("section");section.id="patternMemory";section.className="panel pattern-memory";section.innerHTML='<div class="panel-title"><div><p class="section-label">PROFIT MEMORY</p><h3>Patterns That Make or Lose Money</h3></div><span id="patternMemorySummary">WAITING FOR RESULTS</span></div><div id="patternGrid" class="pattern-grid"><div class="pattern-card"><strong>Waiting for classified trades</strong><small>Patterns will be ranked by actual net money made or lost.</small></div></div>';historyPanel.before(section);}
  const head=document.querySelector(".history-table .row.head");if(head)head.innerHTML="<span>TIME</span><span>DECISION</span><span>RISK</span><span>RESULT</span><span>MONEY OUTCOME</span><span>PATTERN</span>";
  const originalRenderHistory=window.renderHistory;if(typeof originalRenderHistory!=="function")return;
  window.renderHistory=function(history=[]){const rows=document.getElementById("historyRows"),summary=document.getElementById("historySummary");if(!rows||!summary)return originalRenderHistory(history);rows.innerHTML=history.map(row=>{const o=moneyOutcome(row),p=patternOf(row),amount=Number(row.result||0),risk=Number(row.riskAmount||0),time=new Date(row.timeIso).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});return `<div class="row"><span>${time}</span><span>${row.side}</span><span>$${risk.toFixed(2)}</span><span class="${amount>0?"positive":amount<0?"negative":""}">${amount<0?"-":""}$${Math.abs(amount).toFixed(2)}</span><span><span class="money-signal ${o.className}">${o.label} <b class="money-amount">${o.detail}</b> <span class="money-r">${o.r}</span></span></span><span><span class="pattern-pill" title="${p.key}">${p.key}</span></span></div>`;}).join("");const made=history.filter(x=>Number(x.result||0)>0).reduce((s,x)=>s+Number(x.result||0),0),lost=Math.abs(history.filter(x=>Number(x.result||0)<0).reduce((s,x)=>s+Number(x.result||0),0)),net=made-lost;summary.textContent=history.length?`NET ${net>=0?"+":"-"}$${Math.abs(net).toFixed(2)} · made $${made.toFixed(2)} · lost $${lost.toFixed(2)}`:"No closed trades yet";const stats=patternStats(history),grid=document.getElementById("patternGrid"),mem=document.getElementById("patternMemorySummary");if(grid&&mem){const patternNet=stats.reduce((s,x)=>s+x.net,0);mem.textContent=stats.length?`${stats.length} PATTERNS · NET ${patternNet>=0?"+":"-"}$${Math.abs(patternNet).toFixed(2)}`:"WAITING FOR RESULTS";grid.innerHTML=stats.length?stats.slice(0,8).map(x=>`<div class="pattern-card"><strong>${x.key}</strong><span class="pattern-score ${x.net>0?"positive":x.net<0?"negative":"pattern-learning"}">${x.net>0?"MADE MONEY":x.net<0?"LOST MONEY":"FLAT"} ${x.net>=0?"+":"-"}$${Math.abs(x.net).toFixed(2)}</span><small>${x.samples} trades · ${(x.winRate*100).toFixed(0)}% wins · ${x.expectancyR>=0?"+":""}${x.expectancyR.toFixed(2)}R average</small><small>${x.setup} · ${x.trend} · ${x.volatility} volatility · ${x.location} range · ${x.session}</small></div>`).join(""):'<div class="pattern-card"><strong>Waiting for classified trades</strong><small>The backend must attach pattern data to closed trades.</small></div>';}}};
})();
